; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps = 
	olikraus/U8g2@^2.33.16
	bblanchon/ArduinoJson
	madhephaestus/ESP32Servo
	https://github.com/meshtastic/esp32_https_server.git


; |-- U8g2 @ 2.36.18
; |-- ArduinoJson @ 7.4.3
; |-- ESP32Servo @ 3.2.1
; |-- esp32_https_server @ 1.0.0+sha.0c71f38
; |-- LittleFS @ 2.0.0
; |-- WebServer @ 2.0.0
; |-- WiFi @ 2.0.0